function [tracker, name] = sihCreateTracker(cfg)
%SIHCREATETRACKER  Build the multi-object tracker, degrading gracefully.
%
%   [tracker, name] = sihCreateTracker(sihConfig());
%
%   LICENCE NOTE — read this before you promise trackerJPDA to the team:
%     trackerJPDA / trackerGNN live in SENSOR FUSION AND TRACKING TOOLBOX.
%     multiObjectTracker lives in AUTOMATED DRIVING TOOLBOX.
%   If your lab machines only have ADT, trackerJPDA will not exist. This
%   function detects that and falls back, so your pipeline still runs and
%   the interface contract is unaffected either way.
%
%   Preference order: trackerJPDA > trackerGNN > multiObjectTracker
%   JPDA is preferred because it handles the closely-spaced-crossing case
%   (two pedestrians, or a two-wheeler squeezing past an auto) far better
%   than GNN's hard one-to-one assignment.

if nargin < 1, cfg = sihConfig(); end

T = cfg.Tracker;

if ~isempty(which('trackerJPDA'))
    name    = 'trackerJPDA';
    tracker = trackerJPDA( ...
        'FilterInitializationFcn', @initcvekf, ...
        'TrackLogic',              'History', ...
        'AssignmentThreshold',     [T.AssignmentThreshold, T.AssignmentThreshold*3], ...
        'ClutterDensity',          T.ClutterDensity, ...
        'ConfirmationThreshold',   T.ConfirmationThreshold, ...
        'DeletionThreshold',       T.DeletionThreshold, ...
        'MaxNumTracks',            cfg.MaxTracks, ...
        'MaxNumSensors',           numel(cfg.Sensor));

elseif ~isempty(which('trackerGNN'))
    name    = 'trackerGNN';
    tracker = trackerGNN( ...
        'FilterInitializationFcn', @initcvekf, ...
        'TrackLogic',              'History', ...
        'AssignmentThreshold',     [T.AssignmentThreshold, T.AssignmentThreshold*3], ...
        'ConfirmationThreshold',   T.ConfirmationThreshold, ...
        'DeletionThreshold',       T.DeletionThreshold, ...
        'MaxNumTracks',            cfg.MaxTracks, ...
        'MaxNumSensors',           numel(cfg.Sensor));

else
    name    = 'multiObjectTracker';
    tracker = multiObjectTracker( ...
        'FilterInitializationFcn', @initcvekf, ...
        'AssignmentThreshold',     T.AssignmentThreshold, ...
        'ConfirmationThreshold',   T.ConfirmationThreshold, ...
        'DeletionThreshold',       T.DeletionThreshold, ...
        'MaxNumTracks',            cfg.MaxTracks);
end

fprintf('[M1] Tracker: %s (MaxNumTracks=%d)\n', name, cfg.MaxTracks);
end
